### ISSUE TITLE
How do you tackle nested wheres

### ISSUE THREAD

**Issue by kapv89** [Respect/Relational#34]
things like `where foo=1 and (where bar=0 or baz=0)` ?

**Comment by amdrade** [comment]
How to use ```IN``` operation?
```SELECT * FROM table WHERE id IN (1,2,3,4,5)```

**Comment by felipecwb** [comment]
@amdrade

This can help you: 
https://github.com/Respect/Relational/blob/master/tests/library/Respect/Relational/SqlTest.php#L72-L78

**Comment by amdrade** [comment]
Thanks @felipecwb !!
