### ISSUE TITLE
\Respect\Data\Styles\Sakila Doesn't work

### ISSUE THREAD

**Issue by jaircuevajunior** [Respect/Relational#55]
Sakila Style and every Style which uses the same name convention for both Primary Key and Foreign Key.

When making a simple inner join like:
````
$m->news->news_cat->fetchAll();
````

The mapper gets confused about what is a FK and what is a PK as the logic for both is the same. This way, it assumes the PK as FK and never prints its contents.

Eg:

````
$result = $m->city->country->fetch();
var_dump($result);
/**

object(stdClass)[44]
  public 'last_update' => string '2006-02-15 04:45:25' (length=19)
  public 'country_id' => 
    object(stdClass)[46]
      public 'last_update' => string '2006-02-15 04:44:00' (length=19)
      public 'country' => string 'Afghanistan' (length=11)
      public 'country_id' => 
        &object(stdClass)[46]
  public 'city' => string 'Kabul' (length=5)
  public 'city_id' => 
    &object(stdClass)[44]

**/
````

I think a solution for this is to send the table name for the constructor of the Style. Or similar way which I could differ a PK from a FK even when the convention is the same

**Comment by henriquemoody** [comment]
Fixed on version 0.8.1.

I'm sorry by the late, TBH I was not using this library until few days ago...
