### ISSUE TITLE
Update without fetch

### ISSUE THREAD

**Issue by quintanilhar** [Respect/Relational#66]
Hello guys!

Can I execute update without fetch the item before?

Thanks!

**Comment by henriquemoody** [comment]
I'm little uninformed about Relational since it was splitted to Data, I guess @alganet knows if it's possible or not.

**Comment by felipecwb** [comment]
You can use the SQL and DB class:
[test sample](https://github.com/Respect/Relational/blob/master/tests/library/Respect/Relational/SqlTest.php#L127-L134)

```php
$db = new Db(...);
$db->update('table')
   ->set([
        'column' => 'value to be up to date'
    ])
    ->where([
        'id' => 1
    ])
    ->exec();
```

**Comment by alganet** [comment]
There is a public API, but I don't like it. Maybe we should discuss how to improve it.

```php
$entity = (object) [
    'id' => 123,
    'name' => 'Updated name for id 123'
];
$mapper->markTracked($entity, 'table_name', $entity->id);
$mapper->table_name->persist($entity);
```

I haven't tested, extracted code from [this similar issue](https://github.com/Respect/Relational/issues/11).

**Comment by quintanilhar** [comment]
Oh thanks!

We need update and insert methods I think, suppose that we will use some kind of cache and it will need to do some update operation in the object that was loaded by the cache, now a days it's impossible to do in easy way.

I can help to do this feature! :)

**Comment by henriquemoody** [comment]
Awesome! Feel free to send us a pull request, I just advise you to do this as an optional feature.

**Comment by henriquemoody** [comment]
Since the question as solved, I'm closing this issue.
