### ISSUE TITLE
Errors with contructor method attributes when use entityNamespace.

### ISSUE THREAD

**Issue by jackmakiyama** [Respect/Relational#68]
When I use the `$mapper->entityNamespace = '\\MyApplication\\Entities';` in entities with constructor method attributes is generated php errors. You have a solution for this?

**Comment by henriquemoody** [comment]
What kind of errors do you get?

**Comment by felipecwb** [comment]
[docs Entity Classes](https://github.com/Respect/Relational/blob/master/docs/README.md#entity-classes)
> No mandatory params on the constructor please.

If it's, you can extend and override the method which create the instance.

[Mapper:436-442](https://github.com/Respect/Relational/blob/master/library/Respect/Relational/Mapper.php#L436-L442)

**Comment by jackmakiyama** [comment]
@henriquemoody are warnings and notices errors. Is caused by limitation cited by @felipecwb .

I solved this with `ReflectionClass::newInstanceWithoutConstructor`.
What do you think about it?
