### ISSUE TITLE
How do you execute queries made with the Sql class?

### ISSUE THREAD

**Issue by NindroidX** [Respect/Relational#75]
Hi there!

I'm trying to select specific columns from multiple tables. The multi-join tables section of the documentation pointed me to the Sql class, but I have no idea how to actually run that query, any pointers?

I built the query like this: 

    Sql::select('sales.id, products.name, users.name')
        ->from('sales', 'products', 'users')
        ->where(array(
            "sales.products_id" => "products.id",
            "sales.users_id" => "users.id"
     ));

Sorry if this is really obvious, I couldn't find anything in the documentation, and I didn't see anything obvious in the testing file for the Sql class either.

**Comment by williamespindola** [comment]
The Sql class only creates sql query, is not to execute this statement. 
To run queries you can use [Db](https://github.com/Respect/Relational/blob/master/docs/DB-CLASS.md) class like this:

```php
use Respect\Relational\Db;

$db = new db('your dns connection like pdo');

$db->query(
Sql::select('sales.id, products.name, users.name')
    ->from('sales', 'products', 'users')
    ->where(array(
        "sales.products_id" => "products.id",
        "sales.users_id" => "users.id"
 ))
)-> executeStatement();
```
Our use DB for this:
```php
$db->select('sales.id, products.name, users.name')
      ->from('sales')
      ->innerJoin('products')
      ->on('sales.product_id = products.id')
      ->innerJoin('uses')
      ->on('sales.user_id = uses.id')
      ->where([
            "sales.products_id" => "products.id",
            "sales.users_id" => "users.id"
      ])
      ->fetchAll();
```

**Comment by NindroidX** [comment]
@williamespindola Thank you! I actually tried the first method before I posted my question, but It always results in an empty array for some reason. 

Second version worked like a charm though ( although I did remove the ->where() method ). 

I fixed it before with a regular PDO query, but this is a cleaner way! Thanks again :)

Maybe this can be added to the last part of the documentation?

**Comment by williamespindola** [comment]
Yes we can! Exists a lot of "tricks and tips" in the [tests](https://github.com/Respect/Relational/blob/master/tests/library/Respect/Relational/SqlTest.php) that can be write on documentation. Checkout!

Can we close this issue?
