### ISSUE TITLE
Access to $db property from Mapper

### ISSUE THREAD

**Issue by ricardofontanelli** [Respect/Relational#77]
Is there some way (method) to access the protected $db property from Mapper class? Sometimes I need to build and execute "handmade" queries ( using Db::query('...') ).

**Comment by felipecwb** [comment]
You can extend.

```php
<?php

use Respect\Relational\Mapper;

class MyMapper extends Mapper {
    public function getDb() {
        return $this->db;
    }
}
```

Or you can send a pull request with getDb() method.
