### ISSUE TITLE
O que aconteceu com a versao 0.9@dev?

### ISSUE THREAD

**Issue by mothvix** [Respect/Relational#87]
Quando atualizo o composer preciso voltar pra versão 0.8, que não é o master atual e nao possui métodos importantes como o getDB.

**Comment by mothvix** [comment]
corrigido!

**Comment by augustohp** [comment]
> corrigido!

What rolou?

**Comment by mothvix** [comment]
Não sei, mas eu mandei um whats pro Moody, ele deve ter mexido, pq a versao voltou no composer.

**Comment by henriquemoody** [comment]
De algum modo as versões sumiram no packagist
